### PR TITLE
BUGFIX: Position TemplateNodeCreationHandler to the end

### LINKED ISSUE #45: BUG: Setting the title via template on a document not working
The issue became present again: https://github.com/Flowpack/Flowpack.NodeTemplates/issues/20

there are now actually two handlers we have to fight:
- Neos\Neos\Ui\NodeCreationHandler\DocumentTitleNodeCreationHandler (setProperty("title", is becomes actually redundant with the latter)
- Neos\Neos\Ui\NodeCreationHandler\CreationDialogPropertiesCreationHandler

as suggested by @dimaip once we must implement positioning, as we cannot possibly augment any possible future processor, that changes the title. https://github.com/Flowpack/Flowpack.NodeTemplates/pull/21#pullrequestreview-221024534

sorting will be possible as bugfix via: https://github.com/neos/neos-ui/pull/3511

### PR DESCRIPTION
**Pull request by mhsdesign**
also we dont replace the original one anymore

closes https://github.com/Flowpack/Flowpack.NodeTemplates/issues/45

BLOCKED BY https://github.com/neos/neos-ui/pull/3511

### CODE REVIEW

**Comment by theilm** [comment]
Edit: this comment is outdated ;)

Thanks, @mhsdesign (also for allowing static titles / uriPathSegments, that are not EEL expressions).

Perhaps we could simplify some parts as we do not need to cover the default behaviour any more. I'll think about it...

**Comment by mhsdesign** [comment]
patch is released ^^ https://github.com/neos/neos-ui/releases/tag/8.3.1

**Comment by Sebobo** [comment]
Do we need a min version of the Neos.Ui in our dependencies then?

**Comment by mhsdesign** [comment]
actually yes that would be the cleanest - ill fix that ^^

**Comment by mhsdesign** [comment]
@Sebobo adjusted via e2d9388300adeaa57173160a1bdc8d3f29fc92bc

**Pull request merged**
